language: go

go:
  - tip

install:
  - export PATH=$HOME/gopath/bin:$PATH
  - export GO15VENDOREXPERIMENT=1

script:
  - make test

before_deploy:
  - make build

deploy:  
  provider: releases
  api_key: ${GITHUB_KEY}
  file_glob: true
  file: "pkg/remote_syslog*"
  skip_cleanup: true
  on:
    tags: true
